[
  "chatgpt"
  "adguard"
  "tailscale-app"
  "crossover"
  "steam"
  "balenaetcher"
  "gog-galaxy"
  "playcover-community"
  "openvpn-connect"
  "pycharm"
  # "codex-app"  # Renamed to chatgpt
  "firefox"
  "autofirma"
  "intellij-idea"
  "prismlauncher"
  "webstorm"
  "google-chrome"
]
